sign_up:
    path:       /auth/signup
    controller: App\Controller\SignUp

profile:
    path:       /auth/profile
    controller: App\Controller\Profile

auth:
    path:       /oauth/auth
    controller: App\Controller\Auth

logout:
    path:       /oauth/logout
    controller: App\Controller\Logout
